FROM node:14-alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

COPY . .

RUN npm install react@17.0.2
RUN npm install --verbose

COPY deployment/.env_dev .env
# RUN rm deployment/.env_dev deployment/.env_uat deployment/.env_prod

# start app
RUN npm run build
EXPOSE 3000

CMD npm start
