FROM node:14-alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

COPY . .

RUN npm install

COPY deployment/.env_azure_prod .env
# RUN rm deployment/.env_dev deployment/.env_uat deployment/.env_prod

# start app
RUN npm run build
EXPOSE 3000

CMD npm start